# Please refer to the wiki page located at https://github.com/TheComputerizer/Music-Triggers/wiki
# or the discord server located at https://discord.gg/FZHXFYp8fc
# for any specific questions you might have regarding the main config file

[triggers]
	[triggers.time]
		start_hour = "16"
		priority = "10"
		time_bundle = "night"
		identifier = "Night"
		fade_in = "40"
		fade_out = "40"
		end_hour = "0"
	[triggers.generic]
		fade_in = "40"
		fade_out = "40"
[songs]
	[songs.relic9]
		triggers = [ "time-Night" ]
	[songs.relic6]
		triggers = [ "time-Night" ]
	[songs.relic4_2]
		triggers = [ "time-Night" ]
	[songs.relic4_1]
		triggers = [ "time-Night" ]
	[songs.relic2]
		triggers = [ "time-Night" ]
	[songs.universal]
	[songs.silicontransmitterdecay]
		triggers = [ "generic" ]
	[songs.silicontransmitterruin]
		triggers = [ "time-Night" ]
	[songs.silicontransmittercompress]
	[songs.godseyesarelikemymotherseyes]
		triggers = [ "menu" ]
	[songs.heavenexistsandisfullofpoorpeople]
		triggers = [ "generic" ]
	[songs.thankyouforgivingsomuch]
		triggers = [ "generic" ]
	[songs.thegloriousexperienceofdyingpeacefully]
		triggers = [ "generic" ]
	[songs.wheredoyouhideinthebrightlight]
		triggers = [ "generic" ]
