ServerEvents.recipes(e => {

    //I'd rather shove a light bulb up my ass and shatter it than remove these one by one with the .mcmeta
    e.remove({ output: 'chemlib:helium', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:lithium', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:beryllium', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:boron', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:carbon', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:nitrogen', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:oxygen', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:fluorine', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:neon', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:sodium', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:magnesium', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:aluminum', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:silicon', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:phosphorus', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:sulfur', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:chlorine', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:argon', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:potassium', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:calcium', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:scandium', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:titanium', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:vanadium', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:chromium', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:manganese', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:iron', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:cobalt', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:nickel', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:copper', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:zinc', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:gallium', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:germanium', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:arsenic', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:selenium', type: 'alchemistry:fusion' })
    e.remove({ output: 'chemlib:bromine', type: 'alchemistry:fusion' })

})
