ServerEvents.recipes(e => {
    //I dont know why vintage improvement recipes refuse to be removed through the pack.mcmeta, forgive me elocin

    //Plates
    e.remove({ output: 'chemlib:aluminum_plate', type: 'create:pressing' })
    e.remove({ output: 'chemlib:lead_plate', type: 'create:pressing' })
    e.remove({ output: 'chemlib:uranium_plate', type: 'create:pressing' })
    e.remove({ output: 'chemlib:silver_plate', type: 'create:pressing' })
    e.remove({ output: 'chemlib:nickel_plate', type: 'create:pressing' })

    //Rods
    e.remove({output: 'vintageimprovements:aluminum_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:bronze_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:cobalt_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:constantan_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:enderium_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:invar_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:lead_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:lumium_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:nickel_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:osmium_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:palladium_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:platinum_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:refined_glowstone_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:refined_obsidian_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:rhodium_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:signalum_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:silver_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:steel_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:tin_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:uranium_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:andesite_rod', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:vanadium_rod', type: 'minecraft:crafting_shaped'})

    //Wires
    e.remove({output: 'vintageimprovements:aluminum_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:bronze_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:cobalt_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:constantan_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:enderium_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:invar_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:lead_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:lumium_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:nickel_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:osmium_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:palladium_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:platinum_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:refined_glowstone_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:refined_obsidian_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:rhodium_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:signalum_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:silver_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:steel_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:tin_wire', type: 'minecraft:crafting_shaped'})
    e.remove({output: 'vintageimprovements:uranium_wire', type: 'minecraft:crafting_shaped'})

    //Helve Hammer
    e.remove({output: 'thermal:netherite_plate', type: 'vintageimprovements:hammering'})
})
