- name: Run latest-tag
  uses: EndBug/latest-tag@latest
  with:
    # You can change the name of the tag or branch with this input.
    # Default: 'latest'
    ref: latest

    # If a description is provided, the action will use it to create an annotated tag. If none is given, the action will create a lightweight tag.
    # Default: ''
    description: Newest Compression Release

    # Force-update a branch instead of using a tag.
    # Default: false
    force-branch: true

    # Directory to use when executing git commands
    # Default: '${{ github.workspace }}'
    git-directory: ${{ github.workspace }}
